Repository python/mypy, pull requests merged in 2022-09, with the labels that each got.

#12822 Improve error message for partial None with `--local-partial-types`
  mypy/messages.py
  test-data/unit/check-inference.test
  test-data/unit/fine-grained.test
Labels: upnext

#13683 Major update to "using mypy with existing codebase"
  docs/source/existing_code.rst
Labels: documentation

#13682 Mention files confval in "specifying code to check"
  docs/source/running_mypy.rst
Labels: documentation

#13401 Use --no-implicit-optional by default
  docs/source/command_line.rst
  docs/source/config_file.rst
  docs/source/kinds_of_types.rst
  mypy/fastparse.py
  mypy/main.py
  mypy/options.py
  test-data/unit/check-classes.test
  test-data/unit/check-fastparse.test
  test-data/unit/check-flags.test
  test-data/unit/check-functions.test
  test-data/unit/check-kwargs.test
  test-data/unit/check-optional.test
  test-data/unit/check-varargs.test
  test-data/unit/fine-grained.test
  test-data/unit/fixtures/tuple.pyi
  test-data/unit/fixtures/typing-namedtuple.pyi
Labels: upnext

#9636 Make --namespace-packages the default
  docs/source/command_line.rst
  docs/source/config_file.rst
  docs/source/running_mypy.rst
  mypy/build.py
  mypy/main.py
  mypy/options.py
  test-data/unit/check-modules.test
  test-data/unit/fine-grained-modules.test
  test-data/unit/semanal-errors.test
Labels: affects-typeshed, upnext

#13542 Show error codes by default
  docs/source/command_line.rst
  docs/source/config_file.rst
  docs/source/error_codes.rst
  docs/source/type_inference_and_annotations.rst
  mypy/build.py
  mypy/config_parser.py
  mypy/dmypy_server.py
  mypy/errors.py
  mypy/fastparse.py
  mypy/main.py
  mypy/options.py
  mypy/test/helpers.py
  mypy/test/testcheck.py
  mypy/test/testcmdline.py
  mypy/test/testdaemon.py
  mypy/test/testerrorstream.py
  mypy/test/testparse.py
  mypy/test/testpep561.py
  mypy/test/testpythoneval.py
  mypy/test/teststubtest.py
  mypy/util.py
  mypy_self_check.ini
  mypyc/errors.py
  mypyc/test/testutil.py
  test-data/unit/check-errorcodes.test
  test-data/unit/check-flags.test
  test-data/unit/daemon.test
Labels: upnext

#13516 Flip the default for recursive aliases flag
  mypy/main.py
  mypy/options.py
  mypy/semanal.py
  mypy/semanal_namedtuple.py
  mypy/semanal_newtype.py
  mypy/semanal_typeddict.py
  mypy/typeanal.py
  test-data/unit/check-classes.test
  test-data/unit/check-dataclasses.test
  test-data/unit/check-incremental.test
  test-data/unit/check-namedtuple.test
  test-data/unit/check-newsemanal.test
  test-data/unit/check-recursive-types.test
  test-data/unit/check-type-aliases.test
  test-data/unit/check-typeddict.test
  test-data/unit/check-unions.test
  test-data/unit/fine-grained.test
  test-data/unit/pythoneval.test
Labels: upnext
