Repository python/mypy, pull requests merged in 2022-12, with the labels that each got.

#14224 Fix false negatives involving Unions and generators or coroutines
  mypy/checker.py
  test-data/unit/check-async-await.test
  test-data/unit/check-statements.test
Labels: upnext

#14217 [stubtest] Error related to `__all__` must have it in the error path
  mypy/stubtest.py
  mypy/test/teststubtest.py
Labels: topic-stubtest

#14050 (🎁) Add 3.12-dev to CI
  .github/workflows/test.yml
  mypyc/test/test_run.py
  test-requirements.txt
Labels: topic-tests

#14265 Update `stubinfo.py` for recent typeshed changes
  mypy/stubinfo.py
Labels: upnext

#14152 Revert "[mypyc] Use tabs instead of spaces in emitted C code (#14016)"
  mypyc/codegen/emit.py
  mypyc/test/test_emit.py
  mypyc/test/test_emitfunc.py
  mypyc/test/test_emitwrapper.py
Labels: topic-mypyc

#14253 Switch :py:func:`type` to py:class:`type` in type_narrowing.rst
  docs/source/type_narrowing.rst
Labels: documentation

#14270 Stubtest: Improve heuristics for determining whether global-namespace names are imported
  mypy/stubtest.py
  mypy/test/teststubtest.py
Labels: topic-stubtest, upnext

#14277 subtypes: fast path for Union/Union subtype check
  mypy/subtypes.py
  mypy/types.py
Labels: performance, upnext
