Repository python/mypy, pull requests merged in 2023-07, with the labels that each got.

#15297 Handle type[...] same as typing.Type[...] in classmethod 1st arg
  mypy/semanal.py
  test-data/unit/check-selftype.test
Labels: upnext

#15353 Explicit decorated __new__, __class_getitem__ and __init_subclass__
  mypy/checker.py
  mypy/checkmember.py
  mypy/nodes.py
  mypy/semanal.py
  mypy/typeops.py
  test-data/unit/check-selftype.test
Labels: upnext

#15386 Consistently avoid type-checking unreachable code
  mypy/checker.py
  mypyc/test-data/run-misc.test
  test-data/unit/check-classes.test
  test-data/unit/check-fastparse.test
  test-data/unit/check-incremental.test
  test-data/unit/check-inference-context.test
  test-data/unit/check-native-int.test
  test-data/unit/check-statements.test
  test-data/unit/check-typevar-tuple.test
  test-data/unit/check-unreachable-code.test
  test-data/unit/fine-grained.test
Labels: topic-reachability

#15749 Add `__match_args__` to dataclasses with no fields
  mypy/plugins/dataclasses.py
  test-data/unit/check-dataclasses.test
Labels: topic-match-statement, topic-dataclasses
