Repository python/mypy, pull requests merged in 2023-06, with the labels that each got.

#14873 Update semantic analyzer for TypeVar defaults (PEP 696)
  mypy/message_registry.py
  mypy/semanal.py
  mypy/types.py
  test-data/unit/check-parameter-specification.test
  test-data/unit/check-typevar-defaults.test
  test-data/unit/semanal-errors.test
Labels: topic-pep-696

#14988 Improve handling of attribute access on class objects
  mypy/checkmember.py
  test-data/unit/check-class-namedtuple.test
  test-data/unit/check-classes.test
  test-data/unit/pythoneval.test
Labels: topic-metaclasses, affects-mypyc

#15490 Exclude the same special attributes from Protocol as CPython
  mypy/nodes.py
  test-data/unit/check-protocols.test
Labels: upnext
