Repository python/mypy, pull requests merged in 2024-12, with the labels that each got.

#18221 Do not include non-init fields in the synthesized `__replace__` method for dataclasses
  mypy/plugins/dataclasses.py
  test-data/unit/check-dataclasses.test
Labels: upnext

#18217 Preserve block unreachablility when checking function definitions with constrained TypeVars
  mypy/nodes.py
  mypy/treetransform.py
  test-data/unit/check-unreachable-code.test
Labels: upnext

#17712 Implement flag to allow typechecking of untyped modules
  docs/source/command_line.rst
  docs/source/config_file.rst
  docs/source/running_mypy.rst
  mypy/main.py
  mypy/modulefinder.py
  mypy/options.py
  test-data/unit/pep561.test
Labels: upnext

#18192 Make "deprecated" Note a standard Error, disabled by default
  docs/source/command_line.rst
  docs/source/error_code_list2.rst
  mypy/checker.py
  mypy/errorcodes.py
  mypy/main.py
  mypy/options.py
  mypy/typeanal.py
  test-data/unit/check-deprecated.test
  test-data/unit/fine-grained.test
Labels: topic-pep-702

#18090 PEP 702 (@deprecated): descriptors
  mypy/checker.py
  mypy/checkexpr.py
  mypy/checkmember.py
  test-data/unit/check-deprecated.test
Labels: topic-pep-702

#18249 Warn about --follow-untyped-imports
  docs/source/command_line.rst
  docs/source/config_file.rst
  docs/source/running_mypy.rst
Labels: documentation

#18262 Add sphinx_inline_tabs to docs
  docs/requirements-docs.txt
  docs/source/conf.py
  docs/source/running_mypy.rst
Labels: documentation

#18224 Print InspectError traceback in stubgen `walk_packages` when verbose is specified
  mypy/stubgen.py
  mypy/stubutil.py
Labels: topic-stubgen

#17492 Drop support for running with Python 3.8
  .github/workflows/test.yml
  .github/workflows/test_stubgenc.yml
  CONTRIBUTING.md
  docs/source/getting_started.rst
  mypy/defaults.py
  mypy/test/meta/test_parse_data.py
  mypy/util.py
  mypy_self_check.ini
  mypyc/doc/getting_started.rst
  mypyc/test/test_run.py
  pyproject.toml
  setup.py
  test-data/unit/check-columns.test
  test-data/unit/check-errorcodes.test
  test-data/unit/check-functools.test
  test-data/unit/check-generics.test
  test-data/unit/check-incremental.test
  test-data/unit/fine-grained-cache-incremental.test
  test-data/unit/fine-grained.test
  test-data/unit/parse-errors.test
  test-requirements.in
Labels: upnext

#18340 Update pythoncapi_compat.h
  mypyc/lib-rt/pythoncapi_compat.h
Labels: topic-mypyc

#18353 stubtest: Fix crash with numpy array default values
  mypy/stubtest.py
  mypy/test/teststubtest.py
Labels: topic-stubtest

#18350 Fix getargs argument passing
  mypyc/lib-rt/getargs.c
  mypyc/test-data/run-classes.test
Labels: bug, topic-mypyc

#18364 Add some more details for the next release notes
  CHANGELOG.md
Labels: documentation

#18368 Fix markdown formatting
  CHANGELOG.md
Labels: documentation

#17485 Fix --install-types masking failure details
  mypy/main.py
Labels: upnext

#18358 Allow to use Final and ClassVar after python 3.13
  mypy/semanal.py
  mypy/typeanal.py
  test-data/unit/check-final.test
Labels: upnext
