Repository python/mypy, pull requests merged in 2024-01, with the labels that each got.

#14934 Support type stub generation for `staticmethod`
  mypy/stubgenc.py
  test-data/pybind11_mypy_demo/src/main.cpp
  test-data/pybind11_mypy_demo/stubgen-include-docs/pybind11_mypy_demo/basics.pyi
  test-data/pybind11_mypy_demo/stubgen/pybind11_mypy_demo/basics.pyi
Labels: topic-stubgen

#16703 Support TypedDict functional syntax as class base type
  mypy/semanal.py
  mypy/semanal_typeddict.py
  test-data/unit/check-typeddict.test
Labels: upnext

#16315 Support narrowing unions that include type[None].
  mypy/checker.py
  mypy/checkexpr.py
  test-data/unit/check-narrowing.test
Labels: upnext

#16759 Consider TypeVarTuple to be invariant
  mypy/constraints.py
  mypy/test/testconstraints.py
  test-data/unit/check-typevar-tuple.test
Labels: upnext

#16832 Fix disallow-any errors for Instance types (PEP 696)
  mypy/messages.py
  mypy/typeanal.py
  test-data/unit/check-typevar-defaults.test
Labels: topic-pep-696
