Repository python/mypy, pull requests merged in 2024-10, with the labels that each got.

#17899 PEP 702 (@deprecated): improve the handling of explicit type annotations of assignment statements
  mypy/checker.py
  test-data/unit/check-deprecated.test
Labels: upnext

#17929 [mypyc] Sync pythoncapi_compat.h
  mypyc/lib-rt/bytes_ops.c
  mypyc/lib-rt/getargsfast.c
  mypyc/lib-rt/pythoncapi_compat.h
  mypyc/lib-rt/pythonsupport.h
Labels: topic-mypyc

#17923 [mypyc] Support ellipsis (...) expressions in class bodies
  mypyc/irbuild/classdef.py
  mypyc/test-data/run-classes.test
Labels: upnext

#17931 [mypyc] Use PyGen_GetCode in gen_is_coroutine
  mypyc/lib-rt/pythonsupport.h
Labels: topic-mypyc

#17941 [mypyc] Fix wheel build for cp313-win
  mypyc/lib-rt/pythoncapi_compat.h
Labels: topic-mypyc

#17930 [mypyc] Replace deprecated _PyDict_GetItemStringWithError
  mypyc/lib-rt/getargs.c
Labels: topic-mypyc

#17145 fix: TypeGuard becomes bool instead of Any when passed as TypeVar (fixes #17117)
  mypy/constraints.py
  test-data/unit/check-typeguard.test
  test-data/unit/check-typeis.test
Labels: upnext

#17985 Add initial support for new style TypeVar defaults (PEP 696)
  mypy/checker.py
  mypy/fastparse.py
  mypy/message_registry.py
  mypy/nodes.py
  mypy/semanal.py
  mypy/strconv.py
  mypy/test/testparse.py
  test-data/unit/check-python313.test
  test-data/unit/check-typevar-defaults.test
  test-data/unit/parse-python313.test
Labels: topic-pep-696

#17979 [mypyc] fix relative imports in __init__.py
  mypyc/irbuild/statement.py
Labels: upnext

#18014 Improve for loop index variable type narrowing
  mypy/checker.py
  mypy/nodes.py
  mypy/semanal.py
  test-data/unit/check-inference.test
  test-data/unit/fixtures/for.pyi
Labels: topic-typed-dict, topic-literal-types, topic-type-narrowing

#17926 PEP 702 (@deprecated): consider all possible type positions
  mypy/checker.py
  mypy/semanal.py
  mypy/server/astdiff.py
  mypy/typeanal.py
  test-data/unit/check-deprecated.test
  test-data/unit/fine-grained.test
Labels: topic-pep-702

#18054 stubgen: add support for PEPs 695 and 696 syntax
  mypy/stubdoc.py
  mypy/stubgen.py
  mypy/stubutil.py
  test-data/unit/stubgen.test
Labels: topic-stubgen, topic-pep-696, topic-pep-695

#17207 Fix enum attributes are not members
  mypy/semanal.py
  mypy/semanal_enum.py
  mypy/typeops.py
  mypy/types.py
  mypyc/test-data/run-classes.test
  test-data/unit/check-enum.test
  test-data/unit/check-python310.test
  test-data/unit/pythoneval.test
Labels: topic-enum, upnext
