Repository python/mypy, pull requests merged in 2025-06, with the labels that each got.

#19200 Add initial changelog entries for 1.17
  CHANGELOG.md
Labels: documentation

#17713 Fix metaclass resolution algorithm
  mypy/checker.py
  mypy/nodes.py
  test-data/unit/check-abstract.test
  test-data/unit/check-classes.test
Labels: upnext

#19085 Support running stubtest in non-UTF8 terminals
  mypy/stubtest.py
Labels: topic-stubtest

#15043 Type ignore comments erroneously marked as unused by dmypy
  mypy/errors.py
  mypy/server/update.py
  test-data/unit/daemon.test
  test-data/unit/fine-grained.test
Labels: topic-daemon, topic-type-ignore, upnext

#18193 Fix `TypeIs` negative narrowing of union of generics
  mypy/checker.py
  mypy/subtypes.py
  test-data/unit/check-typeis.test
Labels: upnext
